#!/bin/bash
#
#
# |--------------------------------------------------------------|
# | The script thank you for Notos (notos.korsan@gmail.com)      |
# |--------------------------------------------------------------|
# | The script was further developed Tiby08 (tiby0108@gmail.com) |
# |--------------------------------------------------------------|
#

if [ "$1" = "" ]; then
  echo "usage: upgradeSeedbox <version>"
  exit
fi

TSFSV=$1

cd /etc/seedbox-from-scratch/
sudo git fetch --all
sudo git stash
sudo git checkout -b $TSFSV origin/$TSFSV
sudo git pull

sudo bash /etc/seedbox-from-scratch/updateExecutables